"""create roadmaps table

Revision ID: 56ff1b2a729c
Revises: 326bb8b76734
Create Date: 2026-10-09 18:28:21.408940

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56ff1b2a729c"
down_revision: str | Sequence[str] | None = "326bb8b76734"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roadmaps",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("choices", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roadmaps_id"), "roadmaps", ["id"], unique=False)
    op.create_index(op.f("ix_roadmaps_user_id"), "roadmaps", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roadmaps_user_id"), table_name="roadmaps")
    op.drop_index(op.f("ix_roadmaps_id"), table_name="roadmaps")
    op.drop_table("roadmaps")
    # ### end Alembic commands ###
